[package]
name = "doubly-linked-list-rust"
version = "0.1.0"
authors = ["PiotrDudko <piotrd@radcode.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
